### ISSUE TITLE
6 pads per LED, or 8?

### ISSUE THREAD

**Issue by R-OLE** [adafruit/DotStar-2020-8x8-Matrix-PCB#1]
Your datasheet on Adafruit's [LED Dotstar 2020 product page](https://www.adafruit.com/product/3341) links to an (older? wrong, since the color profile product change?) datasheet that shows on its front page a picture of the bottom of the package with two pads on the centerline of the chip.
The same datasheet then does NOT show those two pads in the physical dimensions section on page two, but rather a odd sideways "hat" shaped pad, without any dimensions.
And again on your [product page](https://www.adafruit.com/product/3341), the bottom of the LED is shown, viewed sitting on a US quarter, and it clearly shows there are two central pads.

**Q**: Is this a current datasheet for the Dotstar 2020's parts you're selling?
**Q**: Is this a current datasheet for the Dotstar 2020's you're using on boards?
**Q**: Are there actually not any pads here on some version of these LEDs you used to build these boards?

Which brings us to the design - the 2020 LED footprint you used here have potential issues from ignoring these two pads if folks are trying to re-use your design... 

I say potential issues, because if Vdd and GND are exposed by these pads on the underside of these LEDs, it could create real world clearance problems from other components (added decoupling caps?) with pads near an LED's centerline, or even short circuits if copper is exposed if there are vias under the centerline of the LED, if said vias are not tented over with soldermask like you have on your board (even then it is not foolproof - soldermasks can have holes from the bare board fabricator or be damaged during handling and/or assembly).

I recognize this was a tight design, probably aimed at getting these LEDs as close as possible, while keeping it as cost effective as possible (nicely done, BTW). And one way to do that would be to make sure this layout has no exposed vias or other copper under the LEDs or near their centerline's edge to cause problems with these central pads. 
It is a bit of sleight of hand to do that, and can surely be considered acceptable when the issues are **clearly stated** and understood. Not so nice when it is a hidden "feature".

Off the top of my head, I'd say this tradeoff has the following detractions, to be traded off against increased component density:
- reduces the power dissipation path available to the LEDs (LEDs run hotter, or should be run as long or brightly),
- reduces the power delivery "copper width" to the LED (increases chances of starving the LED and/or resetting the controller die inside)(not so much with your surface flooded power and ground planes),
- raises potential gotcha's for unsuspecting souls following in your footsteps, as I outlined above.

It is nice when there is a text file to share some notes and guidelines, just as many designers include in their zipped up files to be sent off for build. Of course the Readme.md file could provide this same function...

Aside and regardless of the above, **thank you** very much for sharing this design with the world.

**Comment by ladyada** [comment]
hiya, we just dont connect the mysterious center pads. if you make the PCB as uploaded with solder mask and no via exposure, then we've had no problems. we'll add a note to the readme.

**Comment by ladyada** [comment]
we have no other datasheet than what is on the product page. these LEDs are poorly documented!

**Comment by ladyada** [comment]
if you have other manufacturing insights you'd like to add please submit a PR for the readme or other documents! :)
